APT::FTPArchive::Release {
  Origin "oddzen";
  Label "oddzen";
  Suite "stable";
  Codename "trixie";
  Architectures "amd64";
  Components "main";
  Description "Oddsoul's custom Zen kernel for Debian";
};
